---
title: "Modelling the impact and public health response to COVID-19"
output: html_document
---

With other colleagues at the [Centre for Computational Biology, Uganda Christian University](https://github.com/compbiorg/), we modelled SARS-CoV-2 transmission dynamics in Uganda and published two key policy briefs ([brief 1](https://www.pmldaily.com/investigations/special-reports/2020/05/v.html) and [brief 2](https://www.pmldaily.com/investigations/special-reports/2020/05/policybrief-experts-warn-that-exclusive-use-of-face-masks-may-not-be-useful-as-lifting-of-covid-19-lockdown-beckons.html)) and a [manuscript](http://dx.doi.org/10.2139/ssrn.3633199). This work informed that truck drivers posed a threat to spark a community epidemic in the country, which has actually been the case. Our models also showed that social distancing combined with use of face-masks would contain the epidemic but exclusive use of face-masks would not.

Following the second wave of COVID-19 in Uganda we conducted modelling predictions for the third wave of COVID-19 in Uganda. This was was published in a [policy brief](https://www.newvision.co.ug/articledetails/110014) in local print and online media. Based on our modelling approaches, we predicted that the country was likely to experience a third wave early 2022 that would warrant another lockdown, if adequate vaccination was not achieved for more than half of the nation’s population. In addition, our models showed that vaccination and testing efforts needed to be supplemented by a continued sensitization of adherence to the SOPs even after receipt of the vaccine.

Again, under COVID-19, I am part of the  [COAST (End-to-end AI and data systems for targeted surveillance and management of COVID-19 and future pandemics affecting Uganda (COAST)](https://coastv1-a7dd67bb-d488-44c3-ba50.cranecloud.io/) modelling workstream where we are using large datasets from radio transcripts on COVID-19 community voices, human mobility data, air qaulity data and data on meteorological conditions (weather) and other data to inform data-driven modelling (statistical, machine learning and mathematical forecasting models) of COVID-19 epidemic dynamics in Uganda.



