---
title: "Air Pollution, Human Mobility and Transmission of Respiratory Pathogens"
output: html_document
---

Working with collaborators from [AirQo](https://www.airqo.net/), we explored the viability of using ground monitored air quality data as an alternative to aggregated location data from mobile phones, as a measure of human mobility in two cities in Uganda. We observed pollution levels for fine particulate matter (PM2.5) that were above WHO guideline limits in both cities in Uganda even during COVID-19 lockdowns despite some improvement in air quality during these periods. The institution of restrictions also led to an increase in residential mobility and a decrease in non-residential mobility. Air quality improved with stringency of movement restrictions which was positively correlated with movement in residential places and negatively correlated with movement in non-residential places. Furthermore, in a multivariable analysis, air quality was independently positively correlated with movement in non-residential places and negatively correlated with residential mobility. Taken together, these findings suggest that air quality data closely mirrors human mobility data and could thus be used as a proxy to human movement patterns in these places, and consequently a measure of transmission of infectious diseases especially respiratory pathogens, SARS-CoV-2 inclusive.  

This work entitled [Air pollution and mobility patterns in two Ugandan cities during COVID-19 mobility restrictions suggest the validity of air quality data as a measure for human mobility](https://link.springer.com/article/10.1007/s11356-022-24605-1) was published in Environmental Science and Pollution Research.