---
title: "Publications"
output: html_document
---

* Babirye, S. R., Nsubuga, M., Mboowa, G., Batte, C., Galiwango, R., & Kateete, D. P. (2024). Machine learning-based prediction of antibiotic resistance in Mycobacterium tuberculosis clinical isolates from Uganda. BMC Infectious Diseases, 24(1), 1391. https://doi.org/10.1186/s12879-024-10282-7

* Rawson, T. M., Zhu, N., Galiwango, R., Cocker, D., Islam, M. S., Myall, A., Vasikasin, V., Wilson, R., Shafiq, N., Das, S., & Holmes, A. H. (2024). Using digital health technologies to optimise antimicrobial use globally. The Lancet Digital Health, 6(12), e914–e925. https://doi.org/10.1016/S2589-7500(24)00198-5

* Mayito, J., Tumwine, C., Galiwango, R., Nuwamanya, E., Nakasendwa, S., Hope, M., Kig-
gundu, R., Byonanebye, D. M., Dhikusooka, F., Twemanye, V., Kambugu, A., & Kakooza, F.
(2024). Combating Antimicrobial Resistance Through a Data-Driven Approach to Optimize
Antibiotic Use and Improve Patient Outcomes: Protocol for a Mixed Methods Study. JMIR
Research Protocols, 13, e58116. https://doi.org/10.2196/58116

* Tindi, K. B. B., Kalungi, A., Kinyanda, E., Gelaye, B., Martin, A. R., Galiwango, R., Ssembajjwe, W., Kirumira, F., Pretorius, A., Stevenson, A., Newton, C. R. J. C., Stein, D. J., Atkinson, E. G., Mwesiga, E. K., Kyebuzibwa, J., Chibnik, L. B., Atwoli, L., Baker, M., Alemayehu, M., . . . Akena, D. H. (2024). Psychological Distress Among Ethnically Diverse Participants From Eastern and Southern Africa. JAMA Network Open, 7(10), e2438304. https://doi.org/10.1001/jamanetworkopen.2024.38304

* Nsubuga, M., Galiwango, R., Jjingo, D. et al. Generalizability of machine learning in predicting antimicrobial resistance in E. coli: a multi-country case study in Africa. BMC Genomics 25, 287 (2024). https://doi.org/10.1186/s12864-024-10214-4

* Aruhomukama, D., Galiwango, R., Meehan, C. J., & Asiimwe, B. (2024). Enhancing genomics and bioinformatics access in Africa: An imperative leap. The Lancet Microbe, 0(0). https://doi.org/10.1016/S2666-5247(23)00408-1

* Nabakooza, G., Owuor, D. C., de Laurent, Z. R., Galiwango, R., Owor, N., Kayiwa, J. T., Jjingo, D., Agoti, C. N., Nokes, D. J., Kateete, D. P., Kitayimbwa, J. M., Frost, S. D. W., & Lutwama, J. J. (2023). Phylogenomic analysis uncovers a 9-year variation of Uganda influenza type-A strains from the WHO-recommended vaccines and other Africa strains. Scientific Reports, 13(1), 5516. https://doi.org/10.1038/s41598-023-30667-z

* Galiwango, R., Bainomugisha, E., Kivunike, F. et al. Air pollution and mobility patterns in two Ugandan cities during COVID-19 mobility restrictions suggest the validity of air quality data as a measure for human mobility. Environ Sci Pollut Res 30, 34856–34871 (2023). https://doi.org/10.1007/s11356-022-24605-1

* Kiragga AN, Najjemba L, Galiwango R, Banturaki G, Munyiwra G, Iwumbwe I, et al. (2023) Community purchases of antimicrobials during the COVID-19 pandemic in Uganda: An increased
risk for antimicrobial resistance. PLOS Glob Public Health 3(2): e0001579. https://doi.org/10.1371/journal.pgph.0001579

* Nabakooza, G., Galiwango, R., Frost, S. D. W., Kateete, D. P., & Kitayimbwa, J. M. (2022). Molecular Epidemiology and Evolutionary Dynamics of Human Influenza Type-A Viruses in Africa: A Systematic Review. Microorganisms, 10(5), 900. MDPI AG. Retrieved from http://dx.doi.org/10.3390/microorganisms10050900

* Kayondo, H. W., Ssekagiri, A., Nabakooza, G., Bbosa, N., Ssemwanga, D., Kaleebu, P., Mwalili, S., Mango, J. M., Leigh Brown, A. J., Saenz, R. A., Galiwango, R., & Kitayimbwa, J. M. (2021). Employing phylogenetic tree shape statistics to resolve the underlying host population structure. BMC Bioinformatics, 22(1), 546. https://doi.org/10.1186/s12859-021-04465-1

* Daudi Jjingo, Gerald Mboowa, Ivan Sserwadda, Robert Kakaire, Davis Kiberu, Marion Amujal, Ronald Galiwango, David Kateete, Moses Joloba, Christopher C Whalen, Bioinformatics mentorship in a resource limited setting, Briefings in Bioinformatics, 2021;, bbab399, https://doi.org/10.1093/bib/bbab399.

* Miller, P.B., Zalwango, S., Galiwango, R. et al. Association between tuberculosis in men and social network structure in Kampala, Uganda. BMC Infect Dis 21, 1023 (2021). https://doi.org/10.1186/s12879-021-06475-z.

* Yassine, E., Galiwango, R., Ssengooba, W., Ashaba, F., Joloba, M. L., Zalwango, S., Whalen, C. C., & Quinn, F. (2021). Assessing a transmission network of Mycobacterium tuberculosis in an African city using single nucleotide polymorphism threshold analysis. MicrobiologyOpen, 10(3),e1211. https://doi.org/10.1002/mbo3.1211.

* Joseph Ssebuliba, Doreen Mbabazi Ssebuliba, Juliet Nakakawa Nsumba, Ronald Galiwango, Hassan Kayondo, Henry Kasumba, Martha Kirabo, Agnes Namyalo, James Bumba, Letisha
Najjemba, Bernard Molho Bwambale, Vincent Arumadri, Agnes Kiragga and John Kitayimbwa., (2021, July 28). Experts predict when third wave will hit Uganda if SOPs are not adhered to. New Vision, p.3. Available online at: https://www.newvision.co.ug/articledetails/110014
or https://www.newvision.co.ug/articledetails/110273.

* Kiragga, A., Kitayimbwa, J., Galiwango, R. and Mbonye, A., (2020, May 9). Dons Advise on Lockdown Lifting. New Vision, p.26. Available online at: https://www.pmldaily.com/investigations/special-reports/2020/05/v.html.

* Kiragga, A., Kitayimbwa, J., Galiwango, R. and Mbonye, A., (2020, May 18). COVID-19: Experts Caution on Exclusive Use of Masks. New Vision, p.4. Available online at: https://www.pmldaily.com/investigations/special-reports/2020/05/policybrief-experts-warn-that-exclusive-use-of-face-masks-may-not-be-useful-as-lifting-of-covid-19-lockdown-beckons.html. 

* Galiwango, Ronald and Kitayimbwa, John and Kiragga, Agnes N. and Atkins, Katherine E. and Brown, Andrew Leigh and Mbonye, Anthony K., Modelling the Impact and Public Health Response to COVID-19 in Uganda (6/18/2020). Available at SSRN: https://ssrn.com/abstract=3633199 or http://dx.doi.org/10.2139/ssrn.3633199.  

* Galiwango, Ronald; Characterization and Prevention of Tuberculosis Transmission Using Social Networks of TB Patients, Pathogen Whole Genome Sequencing and Mathematical Modeling,University of Georgia. ProQuest Dissertations Publishing, 2019. 27546331. Available at
https://scholar.google.com/scholar?oi=bibs&cluster=4325666414142763784&btnI=1&hl=
en

* Wajja, A., Kizito, D., Nassanga, B., Nalwoga, A., Kabagenyi, J., Kimuda, S., Galiwango, R., Mutonyi, G., Vermaak, S., Satti, I., Verweij, J., Tukahebwa, E., Cose, S., Levin, J., Kaleebu, P., Elliott, A. M., & McShane, H. (2017). The effect of current Schistosoma mansoni infection on the immunogenicity of a candidate TB vaccine, MVA85A, in BCG-vaccinated adolescents: An open-label trial. PLOS Neglected Tropical Diseases, 11(5), e0005440. https://doi.org/10.1371/journal.pntd.0005440. 

* Conference Abstract: James Smith: James Smith, Ronald Galiwango, Argyris Zardilis, Albert Koulman & Julian Grin (2015). Stochastic Process & Mixture Models of Fatty Acid & Lipid Metabolism form a Novel Strategy for Obtaining Status Biomarkers; MMH 2015 1st International Conference on Computational Modeling of Metabolic Health, Inflammation and Diabetes; University of Cambridge, Cambridge, UK. https://www.researchgate.net/profile/James_Smith97/publication/305432116_Infinite_Mixture_Dirichlet_Process_Reveals_a_Landscape_of_Metabolic_Nutritional_States_of_Fatty_Acids_in_a_Population/links/578e8bbb08ae81b4466ec9d1/Infinite-Mixture-Dirichlet-Process-Reveals-a-Landscape-of-Metabolic-Nutritional-States-of-Fatty-Acids-in-a-Population.pdf

* Conference Abstract: Timothy Mwanje Kintu: Timothy Mwanje Kintu, Mugume Twinamatsiko Atwine, Ronald Galiwango, Christine Sekaggya-Wiltshire, Barbara Castelnuovo (2023, August 30). Machine Learning-Based Identification of Predictors Influencing Sub-Therapeutic Rifampicin Concentra- tions in HIV/TB Co-Infected Patients. Deep Learning Indaba 2023. https://openreview.net/ forum?id=GVWNLiqQvG

* Complete list of works and publications can be found using ORCID ID: https://orcid.org/0000-0002-5962-151X.


